### ISSUE TITLE
issue with estimateWindowThreshold function: Error in chol.default(Sigma) 

### ISSUE THREAD

**Issue by ggzheng** [christpa/DMRScan#13]
Hi, 

Sorry to interrupt, I am having an issue with estimateWindowThreshold function. The important sampling seems not stable to me. It failed (code and error attached below), but the second time I re-ran the code it worked. I am not sure what caused the "sampling" failed here.

My code:
n.CpG # 12761
window.sizes <- 3:7
window.thresholds.importancSampling <- estimateWindowThreshold(nProbe = n.CpG, windowSize = window.sizes, method = "sampling", mcmc = 10000)

My error message:
Error in chol.default(Sigma) : 
  the leading minor of order 13 is not positive definite
Calls: estimateWindowThreshold ... estimateThreshold -> t -> importantSampling -> chol -> chol.default
Execution halted

Thanks a lot!

**Comment by christpa** [comment]
Hi Yuanchao,

I'm aware of some of the stability issues for multiple window sizes when the # CpG gets low. However, I'm not able to replicate your issue with the number of sites > 10000. 

The stability issues is a numerical issue related to matrix factorisation, that in theory should work fine, but the solution is to close to a singularity and the numerical algorithms fail to solve the Cholesky factorisation. 

If this is a continuous issue, I would suggest to use a fixed window size instead of a vector of different window sizes, which tend to be much more stable. 

Best
Christian

**Comment by ggzheng** [comment]
Hi Christian,

Thanks for your explanation and replying so fast. I wonder if you have a recommended fixed window size to use. 

Zheng

**Comment by christpa** [comment]
Hi Zheng,

It depends a bit on the number of CpGs and the distribution of the spacing between them, but my preference is for stability so something between 5 to 10 is usually a good compromise. 

Best
Christian

**Comment by christpa** [comment]
I'm closing this ticket. Feel free to comment or open a new one if there are remaining issues. 

Christian
